#theme: jekyll-theme-cayman
#remote_theme: vfong/jekyll-theme-tao
#remote_theme: polterguy/aista-jekyll
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: SOLID Jazz website
description: The official website for Whitney High School's SOLID Jazz club.
logo: /assets/img/<SOLID Jazz logo.jpg>
