#theme: jekyll-theme-cayman
#remote_theme: vfong/jekyll-theme-tao
#remote_theme: polterguy/aista-jekyll
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: SOLID Jazz website
description: The official website for Whitney High School's SOLID Jazz club.
logo: ./T-shirt Logo.heic
email: whssolidjazz@gmail.com

platforms:
  - name: Instagram
    icon: <i class="fa-brands fa-instagram"></i>
    link: https://www.instagram.com/whssolidjazz/?hl=en
  - name: YouTube
    icon: <i class="fa-brands fa-youtube"></i>
    link: https://www.youtube.com/channel/UCwTgxJHb8H2E9NzacMFTfhA
    
navigation:
  - name: Home Page
    link: ./
    sublist:
      -name: What is our goal?
       link: ./What is our goal?
      -name: Meet the 2022-2023 Cabinet!
       link: ./Meet the 2022-2023 Cabinet!
      -name: Rehearsals
       link: ./Rehearsals
      -name: Previous Performances
       link: ./Previous Performances 
